/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as OfferRouteRouteImport } from './routes/offer/route'
import { Route as InventoryRouteRouteImport } from './routes/inventory/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryNewRouteImport } from './routes/inventory/new'
import { Route as InventoryComponentIdRouteImport } from './routes/inventory/$componentId'

const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRouteRoute = OfferRouteRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRouteRoute = InventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InventoryRouteRoute,
} as any)
const InventoryComponentIdRoute = InventoryComponentIdRouteImport.update({
  id: '/$componentId',
  path: '/$componentId',
  getParentRoute: () => InventoryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/offer': typeof OfferRouteRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/inventory/$componentId': typeof InventoryComponentIdRoute
  '/inventory/new': typeof InventoryNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/offer': typeof OfferRouteRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/inventory/$componentId': typeof InventoryComponentIdRoute
  '/inventory/new': typeof InventoryNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/offer': typeof OfferRouteRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/inventory/$componentId': typeof InventoryComponentIdRoute
  '/inventory/new': typeof InventoryNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventory'
    | '/offer'
    | '/config'
    | '/login'
    | '/order'
    | '/inventory/$componentId'
    | '/inventory/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventory'
    | '/offer'
    | '/config'
    | '/login'
    | '/order'
    | '/inventory/$componentId'
    | '/inventory/new'
  id:
    | '__root__'
    | '/'
    | '/inventory'
    | '/offer'
    | '/config'
    | '/login'
    | '/order'
    | '/inventory/$componentId'
    | '/inventory/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventoryRouteRoute: typeof InventoryRouteRouteWithChildren
  OfferRouteRoute: typeof OfferRouteRoute
  ConfigRoute: typeof ConfigRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
    '/inventory/$componentId': {
      id: '/inventory/$componentId'
      path: '/$componentId'
      fullPath: '/inventory/$componentId'
      preLoaderRoute: typeof InventoryComponentIdRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
  }
}

interface InventoryRouteRouteChildren {
  InventoryComponentIdRoute: typeof InventoryComponentIdRoute
  InventoryNewRoute: typeof InventoryNewRoute
}

const InventoryRouteRouteChildren: InventoryRouteRouteChildren = {
  InventoryComponentIdRoute: InventoryComponentIdRoute,
  InventoryNewRoute: InventoryNewRoute,
}

const InventoryRouteRouteWithChildren = InventoryRouteRoute._addFileChildren(
  InventoryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventoryRouteRoute: InventoryRouteRouteWithChildren,
  OfferRouteRoute: OfferRouteRoute,
  ConfigRoute: ConfigRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
